[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
[dependencies.plugin_core]
features = ["plugin_macro"]
git = "https://github.com/End-YYDS/plugin_core"

[lib]
crate-type = ["dylib"]

[package]
edition = "2021"
name = "mod3"
version = "0.1.0"
